### ISSUE TITLE
`nndeploy::dag::getEdge` returns first encountered `Edge*` when 2 or more edges with the same name are in `edge_repository`

### ISSUE THREAD

**Issue by Arpan3323** [nndeploy/nndeploy#111]
Hi, when two or more `EdgeWrapper` in the parameter `vector<EdgeWrapper *> &edge_repository` have the same name, the function below (`nndeploy::dag::getEdge`) returns the first edge only.
https://github.com/nndeploy/nndeploy/blob/4b40b27ab7d226bde6a1ce95f0237481204ea626/framework/source/nndeploy/dag/util.cc#L7-L15

Similar behavior might be observed in the function below (`nndeploy::dag::Graph::getEdge`) but I did not test this.
https://github.com/nndeploy/nndeploy/blob/4b40b27ab7d226bde6a1ce95f0237481204ea626/framework/source/nndeploy/dag/graph.cc#L104-L111

### Example to reproduce
```C++
#include <cstdint>
#include <cstring>
#include <string>
#include <iostream>
#include <array>
#include <algorithm>

#include "nndeploy/dag/edge.h"
#include "nndeploy/dag/util.h"

using namespace nndeploy::dag;
using std::string, std::cout, std::endl, std::vector;

extern "C" int LLVMFuzzerTestOneInput(u_int8_t *Data, size_t Size)
{
    vector<EdgeWrapper *> edge_repository;
    string name(reinterpret_cast<const char*>(Data), Size);
    Edge *edgeA = new Edge(name);
    EdgeWrapper *wrapperA = new EdgeWrapper();
    wrapperA->is_external_ = true;
    wrapperA->edge_ = edgeA;
    wrapperA->name_ = edgeA->getName();
    edge_repository.emplace_back(wrapperA);

    Edge *edgeB = new Edge(name);
    EdgeWrapper *wrapperB = new EdgeWrapper();
    wrapperB->is_external_ = false;
    wrapperB->edge_ = edgeB;
    wrapperB->name_ = edgeB->getName();
    edge_repository.emplace_back(wrapperB);
    auto a = getEdge(edge_repository, name);
    assert(a != nullptr && a == edgeA);
    delete(edgeA);
    delete(wrapperA);
    delete(edgeB);
    delete(wrapperB);
    return 0;
}
```
### Potential fix
My assumption is that `nndeploy::dag::Graph::edge_repository_` allows edges with the same name and manually created `std::vector<EdgeWrapper *>` such as: `vector<EdgeWrapper *> edge_repository;` (from my example) are expected to have edges with the same name. 

If this is true then the current implementation of `nndeploy::dag::getEdge` and `nndeploy::dag::Graph::getEdge` will only return the first `Edge*` it encounters, which should be the intended behavior. If this is not true, then both of these functions can return the wrong `Edge*` when two or more edges with the same name are present.

Let me know if this is the intended behavior and I will close this issue :)

**Comment by Alwaysssssss** [comment]
The potential fix you mentioned is absolutely correct, and Nodes also do not support having the same name.
We need to optimize this part, and it requires a global perspective to review the DAG. I hope we can work together to make the DAG module better.

**Comment by Arpan3323** [comment]
To make `nndeploy::dag` not allow multiple `Edge` with same name and multiple `Node` with same name, I have a few solutions with each having its own advantages and disadvantages. For example:

We can add a private `static std::unordered_set<std::string> usedNames` to `nndeploy::dag::Edge` **and** `nndeploy::dag::Node`. Whenever an `Edge` or `Node` constructor is called, it can look up the given name in `usedNames`:
- If the name is **not present** in `usedNames`, insert the name to `usedNames` and create the object 
- If the name is present in `usedNames`:
    - Throw an exception, notifying that an `Edge` or `Node` with the given name already exists and duplicates are not allowed
    - Add a prefix to the given name to make it distinct, insert the **prefixed name** to `usedNames` and create the object
    - If you have a specific suggestion for this, we can do that instead
    
I would have preferred using `static std::set<std::string>` as it is known to take less space and might perform better if number of elements is small (~100) but I think in our case number of elements is going to be large.

Let me know what you think and if you already had something in mind.

**Comment by Alwaysssssss** [comment]
Thank you very much for your in-depth thoughts and related solutions, which have indeed given me a lot of inspiration. The following are some of my views and discussions regarding each point:

#### The essence of the naming conflict issue
The situation of naming conflicts mainly occurs in `std::vector<EdgeWrapper *> &edge_repository` and `std::vector<NodeWrapper *> node_repository`. For example, when there are two edges with the same name but they don't belong to the same `std::vector<EdgeWrapper *> &edge_repository`, there won't be a problem. This helps us to understand more clearly the specific scope of scenarios where the naming conflict issue has an impact.

#### Returning error codes or `nullptr` (the way mainly implemented by nndeploy through error codes) is better than modifying user-defined names
Because if the user-defined names are silently modified, when an error occurs for the user, it will greatly increase the difficulty of debugging. It will be very hard for the user to locate where the problem exactly lies. Therefore, from the perspective of debugging convenience, this approach is more appropriate.

#### Problems with the global `static std::set<std::string>`
As has been pointed out, there are quite a few problems with establishing a global `static std::set<std::string>`. On the one hand, as the algorithm deployment belongs to incremental development, the number of elements will increase, and the overhead it generates itself will be large. Besides, there are other derivative problems:
- Performance degradation caused by locking: This global variable needs to be locked to ensure thread safety. However, the locking operation will further reduce the performance of the entire system in a multi-threaded environment and affect the running efficiency.
- Overhead of `delete`: Besides the resource management overhead brought by the `new` operation, the `delete` operation also has an overhead, which also affects the overall resource utilization efficiency.

#### Discussion on solutions
- Solving the problem in `Graph`: Considering that `std::vector<EdgeWrapper *> edge_repository` and `std::vector<NodeWrapper *> node_repository` are constructed in `Graph`, it is a feasible idea to solve the naming conflict issue within `Graph`. For example, add member variables `std::set<string> used_node_names_` and `std::set<string> used_edge_names_` in `Graph`. Through such a mechanism, it can be ensured that there will be no naming conflicts, thus avoiding the adverse effects caused by the naming conflict issue from the root. Specifically, when adding elements to `edge_repository` or `node_repository`, first check whether there are already elements with the same name in the corresponding `used_*_names_` sets. If so, perform corresponding error handling to ensure the uniqueness of names.

- A more radical approach and its impact: Establish two new data structures: `struct EdgeRepository` and `struct NodeRepository`, as shown in the code block below. However, currently, the entire `Dag` module is implemented based on `std::vector<EdgeWrapper *> edge_repository` and `std::vector<NodeWrapper *> node_repository`. If this module is modified, it will have a huge impact on the entire system and may involve a large amount of code modification and the re-testing of existing functions.

  // Preliminary design of data structures
  ```cpp
  struct EdgeRepository {
    std::mutex lock_; 
    std::vector<EdgeWrapper *> edge_repository_; 
    std::map<std::string, int> used_node_names_;
    ...
  }
  ```
